In [1]:
d1='pasta is very tasty and affordable'
d2='pasta is not tasty and affordable'

In [2]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer()

In [3]:
result=bow.fit_transform([d1,d2]).toarray()
#toarray() converts a sparse matrix to a regular NumPy array.

In [4]:
result

array([[1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0]], dtype=int64)

In [5]:
d1='pasta is very tasty and affordable'
d2='pasta is not tasty and affordable'

In [7]:
from sklearn.feature_extraction.text import CountVectorizer
bow=CountVectorizer(ngram_range=(1,1))

In [8]:
result=bow.fit_transform([d1,d2]).toarray()

In [9]:
result

array([[1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0]], dtype=int64)

In [10]:
bow=CountVectorizer(ngram_range=(2,2))

In [11]:
r1=result=bow.fit_transform([d1,d2]).toarray()

In [12]:
r1

array([[1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 0]], dtype=int64)

In [13]:
bow=CountVectorizer(ngram_range=(2,3))

In [14]:
r2=bow.fit_transform([d1,d2]).toarray()

In [15]:
r2

array([[1, 0, 0, 1, 1, 0, 0, 1, 0, 1, 1, 1, 1, 1],
       [1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0]], dtype=int64)

In [16]:
bow=CountVectorizer(ngram_range=(3,3))

In [17]:
r3=bow.fit_transform([d1,d2]).toarray()

In [18]:
r3

array([[0, 1, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 0]], dtype=int64)

In [20]:
def fun(d1,d2):
    result=bow.fit_transform([d1,d2]).toarray()
    return result
d1='pasta is very tasty and affordable'
d2='pasta is not tasty and affordable'
fun(d1,d2)

array([[0, 1, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 0]], dtype=int64)

In [9]:
#above all transper to functions
#bag of words
from sklearn.feature_extraction.text import CountVectorizer
def fun(d1,d2):
    bow=CountVectorizer(ngram_range=(1,1))
    result=bow.fit_transform([d1,d2]).toarray()
    print("Vocabulary:",bow)
    print("Vocabulary:",bow.get_feature_names_out())#alfabetical sorted order d1,d2
    print("bow (unigram) Matrix:\n",result)
    return result
d1="pasta is very tasty and affordable"
d2="pasta is not tasty and affordable"
fun(d1,d2)
#Each row = sentence
#Each column = word count based on vocabulary

Vocabulary: CountVectorizer()
Vocabulary: ['affordable' 'and' 'is' 'not' 'pasta' 'tasty' 'very']
bow (unigram) Matrix:
 [[1 1 1 0 1 1 1]
 [1 1 1 1 1 1 0]]


array([[1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0]], dtype=int64)

In [16]:
#2.Bag of Words (Bigram → ngram_range=(2,2))
def fun(d1,d2):
    bow=CountVectorizer(ngram_range=(2,2))
    result=bow.fit_transform([d1,d2]).toarray()
    print("vocabulary(bigrams):",bow.get_feature_names_out())
    print("BoW (Bigram) Matrix:\n",result)                   
    return result
fun(d1,d2)
#Each bigram is a pair of 2 consecutive words.

vocabulary(bigrams): ['and affordable' 'is not' 'is very' 'not tasty' 'pasta is' 'tasty and'
 'very tasty']
BoW (Bigram) Matrix:
 [[1 0 1 0 1 1 1]
 [1 1 0 1 1 1 0]]


array([[1, 0, 1, 0, 1, 1, 1],
       [1, 1, 0, 1, 1, 1, 0]], dtype=int64)

In [17]:
#3. Bag of Words (Trigram → ngram_range=(3,3))
def fun(d1,d2):
    bow=CountVectorizer(ngram_range=(3,3))
    result=bow.fit_transform([d1,d2]).toarray()
    print("vocabulary(trigrams):",bow.get_feature_names_out())#alfabetical sorted three words d1,d2
    print("BoW (Bigram) Matrix:\n",result)
    return result
fun(d1,d2)
#Each trigram is a group of 3 consecutive words.

vocabulary(trigrams): ['is not tasty' 'is very tasty' 'not tasty and' 'pasta is not'
 'pasta is very' 'tasty and affordable' 'very tasty and']
BoW (Bigram) Matrix:
 [[0 1 0 0 1 1 1]
 [1 0 1 1 0 1 0]]


array([[0, 1, 0, 0, 1, 1, 1],
       [1, 0, 1, 1, 0, 1, 0]], dtype=int64)

In [19]:
#4. TF-IDF (Unigram)
from sklearn.feature_extraction.text import TfidfVectorizer
def fun(d1,d2):
    bow=TfidfVectorizer()
    result=bow.fit_transform([d1,d2]).toarray()
    print("vocabulary(trigrams):",bow.get_feature_names_out())
    print("BoW (Bigram) Matrix:\n",result)
    return result
fun(d1,d2)

vocabulary(trigrams): ['affordable' 'and' 'is' 'not' 'pasta' 'tasty' 'very']
BoW (Bigram) Matrix:
 [[0.37863221 0.37863221 0.37863221 0.         0.37863221 0.37863221
  0.53215436]
 [0.37863221 0.37863221 0.37863221 0.53215436 0.37863221 0.37863221
  0.        ]]


array([[0.37863221, 0.37863221, 0.37863221, 0.        , 0.37863221,
        0.37863221, 0.53215436],
       [0.37863221, 0.37863221, 0.37863221, 0.53215436, 0.37863221,
        0.37863221, 0.        ]])

In [33]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer,TfidfVectorizer
#combination
def fun(d1,d2):
    bow=CountVectorizer()
    result=bow.fit_transform([d1,d2]).toarray()
    print("Bag of Words (BoW):")
    print(pd.DataFrame(result,columns=bow.get_feature_names_out()))
    tfidf=TfidfVectorizer()
    result1=tfidf.fit_transform([d1, d2]).toarray()
    print("tf-ide")
    print(pd.DataFrame(result1,columns=tfidf.get_feature_names_out()))
    return result
d1="pasta is very tasty and affordable"
d2="pasta is not tasty and affordable"
fun(d1,d2)

Bag of Words (BoW):
   affordable  and  is  not  pasta  tasty  very
0           1    1   1    0      1      1     1
1           1    1   1    1      1      1     0
tf-ide
   affordable       and        is       not     pasta     tasty      very
0    0.378632  0.378632  0.378632  0.000000  0.378632  0.378632  0.532154
1    0.378632  0.378632  0.378632  0.532154  0.378632  0.378632  0.000000


array([[1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0]], dtype=int64)

In [32]:
import pandas as pd
from sklearn.feature_extraction.text import CountVectorizer, TfidfVectorizer

def fun(d1, d2):
    # Bag of Words
    bow = CountVectorizer()
    result = bow.fit_transform([d1, d2]).toarray()
    print("Bag of Words (BoW):")
    print(pd.DataFrame(result, columns=bow.get_feature_names_out()))
    print()

    # TF-IDF
    tfidf = TfidfVectorizer()
    result1 = tfidf.fit_transform([d1, d2]).toarray()
    print(" TF-IDF:")
    print(pd.DataFrame(result1, columns=tfidf.get_feature_names_out()))
    return result

# Input texts
d1 = "pasta is very tasty and affordable"
d2 = "pasta is not tasty and affordable"

fun(d1, d2)


Bag of Words (BoW):
   affordable  and  is  not  pasta  tasty  very
0           1    1   1    0      1      1     1
1           1    1   1    1      1      1     0

 TF-IDF:
   affordable       and        is       not     pasta     tasty      very
0    0.378632  0.378632  0.378632  0.000000  0.378632  0.378632  0.532154
1    0.378632  0.378632  0.378632  0.532154  0.378632  0.378632  0.000000


array([[1, 1, 1, 0, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 0]], dtype=int64)

## 04/07/2025

In [1]:
d1="pizza is delicious"
d2="pizza is delicious and affordable"

In [2]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [3]:
tf=TfidfVectorizer()

In [4]:
m=tf.fit_transform([d1,d2]).toarray()

In [5]:
m

array([[0.        , 0.        , 0.57735027, 0.57735027, 0.57735027],
       [0.53309782, 0.53309782, 0.37930349, 0.37930349, 0.37930349]])