In [1]:
import numpy as np

In [3]:
h=np.array([140,160,155,170,163,145])
w=np.array([45,48,50,52,53,54])
cv=np.cov(h,w)

In [4]:
cv

array([[127.5       ,  15.6       ],
       [ 15.6       ,  11.46666667]])

In [5]:
cv[0,1]

15.600000000000001

In [6]:
high_inch=h*0.4
weight_lbs=w*2.2

In [7]:
cv2=np.cov(high_inch,weight_lbs)

In [8]:
cv2

array([[20.4       , 13.728     ],
       [13.728     , 55.49866667]])

In [9]:
cv2[0,1]

13.727999999999993

In [10]:
cv3=np.corrcoef(high_inch,weight_lbs)

In [11]:
cv3

array([[1.        , 0.40799131],
       [0.40799131, 1.        ]])

In [12]:
cv3[0,1]

0.4079913091534341

In [13]:
h=np.array([140,160,155,170,163,145])
w=np.array([45,48,50,52,53,54])

In [23]:
from scipy.stats import spearmanr

In [24]:
rho=spearmanr(h,w)

In [25]:
rho

SignificanceResult(statistic=0.3142857142857143, pvalue=0.5440932944606414)